// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MicroservicioCuentaMovimientos.Models;

public partial class DB_CuentaMovimientoContext : DbContext
{
    public DB_CuentaMovimientoContext(DbContextOptions<DB_CuentaMovimientoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CUENTA> CUENTA { get; set; }

    public virtual DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CUENTA>(entity =>
        {
            entity.HasKey(e => e.NumeroCuenta).HasName("PK__CUENTA__E039507A66424E9A");

            entity.Property(e => e.SaldoInicial).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TipoCuenta)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<MOVIMIENTO>(entity =>
        {
            entity.HasKey(e => e.MovimientoId).HasName("PK__MOVIMIEN__BF923C2CD79E9CA6");

            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.Saldo).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TipoMovimiento)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Valor).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.NumeroCuentaNavigation).WithMany(p => p.MOVIMIENTO)
                .HasForeignKey(d => d.NumeroCuenta)
                .HasConstraintName("FK__MOVIMIENT__Numer__403A8C7D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}