// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MicroservicioClientePersona.Models;

public partial class PERSONA
{
    public int PersonaId { get; set; }

    public string Nombre { get; set; }

    public string Genero { get; set; }

    public int Edad { get; set; }

    public string Identificacion { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<CLIENTE> CLIENTE { get; set; } = new List<CLIENTE>();
}